name: Update Kaggle Notebook

on:
  push:
    paths:
      - Youtube_Translation.py
      - kaggle_push.py
      - requirements.txt
      - main.py
      - youtube_fetcher.py
      - transcriber.py
      - summarizer.py
      - email_sender.py
      - config.py
  schedule:
    - cron: '0 11 * * *'

jobs:
  update-kaggle-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Kaggle API token
        run: |
          mkdir -p ~/.kaggle
          echo "$KAGGLE_JSON" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
        env:
          KAGGLE_JSON: ${{ secrets.KAGGLE_JSON }}

      - name: Update Kaggle Notebook
        env:
          KAGGLE_NOTEBOOK_ID: ${{ secrets.KAGGLE_NOTEBOOK_ID }}
          KAGGLE_JSON: ${{ secrets.KAGGLE_JSON }}
        run: |
          python kaggle_push.py

      - name: Write YouTube cookies
        run: echo "$YOUTUBE_COOKIES" > cookies.txt
        env:
          YOUTUBE_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}

      - name: Run YouTube Summary and Email Workflow
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_MAIL: ${{ secrets.GOOGLE_MAIL }}
          GOOGLE_MAIL_KEY: ${{ secrets.GOOGLE_MAIL_KEY }}
          RECEIVER_MAIL: ${{ secrets.RECEIVER_MAIL }}
        run: |
          python main.py 